theme: minima
title: What The Hack
description: A collection of challenge-based hackathons including student guides, coach guides, lecture presentations, sample/template code and sample solutions.
include: [CONTRIBUTING.md]
plugins:
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-relative-links
minima:
  skin: classic
  social_links:
    github: perktime
author:
  name: What The Hack
  email: info@whathehack.com
header_pages:
  - VISUAL-SHOWCASE.md
  - CONTRIBUTING.md